# Site settings
title: The Mungkul, Cottages & Restaurant
email: manager@themungkulcottage.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# my plugins = gemfile
plugins:
  - jekyll-seo-tag

instagram :
  app_id: https://www.instagram.com/the_mungkul_nusapenida/

facebook:
  app_id: https://www.facebook.com/TheMungkul/
  publisher: https://www.facebook.com/TheMungkul/
  admins: https://www.facebook.com/TheMungkul/

# Build settings
markdown: kramdown



